# Generated by Django 5.1.15 on 2026-09-04 09:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('image', models.EmailField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usermaster',
            },
        ),
    ]
