# Generated by Django 5.1.15 on 2026-09-04 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLoginToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('token_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email-token',
            },
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='usermaster',
            table='user-master',
        ),
    ]
