# Generated by Django 5.1.15 on 2026-09-08 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclogintoken',
            name='created_by',
            field=models.CharField(default='SYSTEM', max_length=255),
        ),
        migrations.AddField(
            model_name='magiclogintoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified At'),
        ),
        migrations.AddField(
            model_name='magiclogintoken',
            name='updated_by',
            field=models.CharField(default='SYSTEM', max_length=255),
        ),
        migrations.AddField(
            model_name='plan',
            name='created_by',
            field=models.CharField(default='SYSTEM', max_length=255),
        ),
        migrations.AddField(
            model_name='plan',
            name='updated_by',
            field=models.CharField(default='SYSTEM', max_length=255),
        ),
        migrations.AlterModelTable(
            name='plan',
            table='plans',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed')], default='created', max_length=20)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='db.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
