# Generated by Django 5.1.15 on 2026-09-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_magiclogintoken_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='created_by',
            field=models.CharField(default='SYSTEM', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_by',
            field=models.CharField(default='SYSTEM', max_length=255),
        ),
    ]
