# Generated by Django 5.1.15 on 2026-09-10 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_category_course_coursemodule_technology_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(default='SYSTEM', max_length=255)),
                ('updated_by', models.CharField(default='SYSTEM', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Lesson duration in seconds')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_preview', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='db.coursemodule')),
            ],
            options={
                'db_table': 'lesson',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
