# Generated by Django 5.1.15 on 2026-09-11 07:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(default='SYSTEM', max_length=255)),
                ('updated_by', models.CharField(default='SYSTEM', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('original_key', models.CharField(help_text='S3 key of the original uploaded video', max_length=500)),
                ('hls_key', models.CharField(blank=True, help_text='S3 key of the HLS master playlist', max_length=500, null=True)),
                ('media_job_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Video duration in seconds')),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='Original video size in bytes')),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'video',
                'ordering': ['-created_at'],
            },
        ),
    ]
