# Generated by Django 5.1.15 on 2026-09-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('telugu', 'Telugu'), ('hindi', 'Hindi')], default='english', max_length=30),
        ),
    ]
