# Generated by Django 5.1.15 on 2026-09-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_video_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='course_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
