# Generated by Django 5.1.15 on 2026-09-13 08:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_video_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='course_id',
        ),
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='db.course'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('assigned', 'Assigned')], default='uploaded', max_length=20),
        ),
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_videos', to='db.lesson')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_videos', to='db.video')),
            ],
            options={
                'db_table': 'lesson_video',
                'constraints': [models.UniqueConstraint(fields=('lesson', 'video'), name='unique_lesson_video')],
            },
        ),
    ]
