# Generated by Django 5.1.15 on 2026-09-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_remove_lesson_video_remove_video_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonvideo',
            name='created_by',
            field=models.CharField(default='SYSTEM', max_length=255),
        ),
        migrations.AddField(
            model_name='lessonvideo',
            name='updated_by',
            field=models.CharField(default='SYSTEM', max_length=255),
        ),
        migrations.AlterField(
            model_name='lessonvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='lessonvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified At'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('assigned', 'Assigned')], default='uploaded', max_length=20),
        ),
    ]
