# Generated by Django 5.1.15 on 2026-09-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_lessonvideo_created_by_lessonvideo_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
