# Generated by Django 5.1.15 on 2026-09-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_usermaster_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('telugu', 'Telugu')], default='english', max_length=30),
        ),
    ]
