# Generated by Django 5.1.15 on 2026-09-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_alter_usermaster_mobile_alter_video_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclogintoken',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='magiclogintoken',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='magiclogintoken',
            table='magic_token',
        ),
        migrations.AlterModelTable(
            name='otp',
            table='otp',
        ),
    ]
